COMPANIES = {
    "reliance": {"ticker": "RELIANCE", "name": "Reliance Industries", "mkt": "IN", "sector": "energy-conglomerate"},
    "ril": {"ticker": "RELIANCE", "name": "Reliance Industries", "mkt": "IN", "sector": "energy-conglomerate"},
    "jio": {"ticker": "RELIANCE", "name": "Jio / Reliance", "mkt": "IN", "sector": "telecom-digital"},
    "jio platforms": {"ticker": "RELIANCE", "name": "Jio Platforms", "mkt": "IN", "sector": "telecom-digital"},
    "tcs": {"ticker": "TCS", "name": "Tata Consultancy Services", "mkt": "IN", "sector": "it"},
    "tata consultancy": {"ticker": "TCS", "name": "Tata Consultancy Services", "mkt": "IN", "sector": "it"},
    "infosys": {"ticker": "INFY", "name": "Infosys", "mkt": "IN", "sector": "it"},
    "infy": {"ticker": "INFY", "name": "Infosys", "mkt": "IN", "sector": "it"},
    "wipro": {"ticker": "WIPRO", "name": "Wipro", "mkt": "IN", "sector": "it"},
    "hcltech": {"ticker": "HCLTECH", "name": "HCL Technologies", "mkt": "IN", "sector": "it"},
    "hcl tech": {"ticker": "HCLTECH", "name": "HCL Technologies", "mkt": "IN", "sector": "it"},
    "tech mahindra": {"ticker": "TECHM", "name": "Tech Mahindra", "mkt": "IN", "sector": "it"},
    "hdfc bank": {"ticker": "HDFCBANK", "name": "HDFC Bank", "mkt": "IN", "sector": "bank"},
    "icici bank": {"ticker": "ICICIBANK", "name": "ICICI Bank", "mkt": "IN", "sector": "bank"},
    "sbi": {"ticker": "SBIN", "name": "State Bank of India", "mkt": "IN", "sector": "bank"},
    "state bank": {"ticker": "SBIN", "name": "State Bank of India", "mkt": "IN", "sector": "bank"},
    "axis bank": {"ticker": "AXISBANK", "name": "Axis Bank", "mkt": "IN", "sector": "bank"},
    "kotak": {"ticker": "KOTAKBANK", "name": "Kotak Mahindra Bank", "mkt": "IN", "sector": "bank"},
    "bajaj finance": {"ticker": "BAJFINANCE", "name": "Bajaj Finance", "mkt": "IN", "sector": "nbfc"},
    "bajaj finserv": {"ticker": "BAJAJFINSV", "name": "Bajaj Finserv", "mkt": "IN", "sector": "nbfc"},
    "shriram finance": {"ticker": "SHRIRAMFIN", "name": "Shriram Finance", "mkt": "IN", "sector": "nbfc"},
    "lic": {"ticker": "LICI", "name": "Life Insurance Corporation", "mkt": "IN", "sector": "insurance"},
    "ongc": {"ticker": "ONGC", "name": "ONGC", "mkt": "IN", "sector": "upstream"},
    "oil india": {"ticker": "OIL", "name": "Oil India", "mkt": "IN", "sector": "upstream"},
    "ioc": {"ticker": "IOC", "name": "Indian Oil", "mkt": "IN", "sector": "omc"},
    "indian oil": {"ticker": "IOC", "name": "Indian Oil", "mkt": "IN", "sector": "omc"},
    "bpcl": {"ticker": "BPCL", "name": "Bharat Petroleum", "mkt": "IN", "sector": "omc"},
    "hpcl": {"ticker": "HPCL", "name": "Hindustan Petroleum", "mkt": "IN", "sector": "omc"},
    "gail": {"ticker": "GAIL", "name": "GAIL", "mkt": "IN", "sector": "gas"},
    "ntpc": {"ticker": "NTPC", "name": "NTPC", "mkt": "IN", "sector": "power"},
    "power grid": {"ticker": "POWERGRID", "name": "Power Grid", "mkt": "IN", "sector": "power"},
    "coal india": {"ticker": "COALINDIA", "name": "Coal India", "mkt": "IN", "sector": "coal"},
    "tata power": {"ticker": "TATAPOWER", "name": "Tata Power", "mkt": "IN", "sector": "power"},
    "adani power": {"ticker": "ADANIPOWER", "name": "Adani Power", "mkt": "IN", "sector": "power"},
    "adani enterprises": {"ticker": "ADANIENT", "name": "Adani Enterprises", "mkt": "IN", "sector": "conglomerate"},
    "adani ports": {"ticker": "ADANIPORTS", "name": "Adani Ports", "mkt": "IN", "sector": "ports"},
    "adani green": {"ticker": "ADANIGREEN", "name": "Adani Green", "mkt": "IN", "sector": "renewables"},
    "suzlon": {"ticker": "SUZLON", "name": "Suzlon", "mkt": "IN", "sector": "renewables"},
    "tata steel": {"ticker": "TATASTEEL", "name": "Tata Steel", "mkt": "IN", "sector": "metals"},
    "jsw steel": {"ticker": "JSWSTEEL", "name": "JSW Steel", "mkt": "IN", "sector": "metals"},
    "hindalco": {"ticker": "HINDALCO", "name": "Hindalco", "mkt": "IN", "sector": "metals"},
    "vedanta": {"ticker": "VEDL", "name": "Vedanta", "mkt": "IN", "sector": "metals"},
    "sail": {"ticker": "SAIL", "name": "SAIL", "mkt": "IN", "sector": "metals"},
    "maruti": {"ticker": "MARUTI", "name": "Maruti Suzuki", "mkt": "IN", "sector": "auto"},
    "tata motors": {"ticker": "TATAMOTORS", "name": "Tata Motors", "mkt": "IN", "sector": "auto"},
    "m&m": {"ticker": "M&M", "name": "Mahindra & Mahindra", "mkt": "IN", "sector": "auto"},
    "mahindra": {"ticker": "M&M", "name": "Mahindra & Mahindra", "mkt": "IN", "sector": "auto"},
    "hero motocorp": {"ticker": "HEROMOTOCO", "name": "Hero MotoCorp", "mkt": "IN", "sector": "auto"},
    "bajaj auto": {"ticker": "BAJAJ-AUTO", "name": "Bajaj Auto", "mkt": "IN", "sector": "auto"},
    "eicher": {"ticker": "EICHERMOT", "name": "Eicher Motors", "mkt": "IN", "sector": "auto"},
    "ashok leyland": {"ticker": "ASHOKLEY", "name": "Ashok Leyland", "mkt": "IN", "sector": "cv"},
    "indigo": {"ticker": "INDIGO", "name": "InterGlobe Aviation", "mkt": "IN", "sector": "aviation"},
    "interglobe": {"ticker": "INDIGO", "name": "InterGlobe Aviation", "mkt": "IN", "sector": "aviation"},
    "asian paints": {"ticker": "ASIANPAINT", "name": "Asian Paints", "mkt": "IN", "sector": "paints"},
    "pidilite": {"ticker": "PIDILITIND", "name": "Pidilite", "mkt": "IN", "sector": "chemicals"},
    "ultratech": {"ticker": "ULTRACEMCO", "name": "UltraTech Cement", "mkt": "IN", "sector": "cement"},
    "sun pharma": {"ticker": "SUNPHARMA", "name": "Sun Pharma", "mkt": "IN", "sector": "pharma"},
    "dr reddy": {"ticker": "DRREDDY", "name": "Dr Reddy's", "mkt": "IN", "sector": "pharma"},
    "cipla": {"ticker": "CIPLA", "name": "Cipla", "mkt": "IN", "sector": "pharma"},
    "divis": {"ticker": "DIVISLAB", "name": "Divi's Labs", "mkt": "IN", "sector": "pharma"},
    "itc": {"ticker": "ITC", "name": "ITC", "mkt": "IN", "sector": "fmcg"},
    "hindustan unilever": {"ticker": "HINDUNILVR", "name": "HUL", "mkt": "IN", "sector": "fmcg"},
    "hul": {"ticker": "HINDUNILVR", "name": "HUL", "mkt": "IN", "sector": "fmcg"},
    "nestle": {"ticker": "NESTLEIND", "name": "Nestle India", "mkt": "IN", "sector": "fmcg"},
    "britannia": {"ticker": "BRITANNIA", "name": "Britannia", "mkt": "IN", "sector": "fmcg"},
    "titan": {"ticker": "TITAN", "name": "Titan", "mkt": "IN", "sector": "consumer"},
    "d-mart": {"ticker": "DMART", "name": "Avenue Supermarts", "mkt": "IN", "sector": "retail"},
    "avenue supermarts": {"ticker": "DMART", "name": "Avenue Supermarts", "mkt": "IN", "sector": "retail"},
    "hal": {"ticker": "HAL", "name": "Hindustan Aeronautics", "mkt": "IN", "sector": "defense"},
    "bharat electronics": {"ticker": "BEL", "name": "Bharat Electronics", "mkt": "IN", "sector": "defense"},
    "bhel": {"ticker": "BHEL", "name": "BHEL", "mkt": "IN", "sector": "capital-goods"},
    "l&t": {"ticker": "LT", "name": "Larsen & Toubro", "mkt": "IN", "sector": "infra"},
    "larsen": {"ticker": "LT", "name": "Larsen & Toubro", "mkt": "IN", "sector": "infra"},
    "rvnl": {"ticker": "RVNL", "name": "Rail Vikas Nigam", "mkt": "IN", "sector": "railways"},
    "irctc": {"ticker": "IRCTC", "name": "IRCTC", "mkt": "IN", "sector": "railways"},
    "bharti": {"ticker": "BHARTIARTL", "name": "Bharti Airtel", "mkt": "IN", "sector": "telecom"},
    "airtel": {"ticker": "BHARTIARTL", "name": "Bharti Airtel", "mkt": "IN", "sector": "telecom"},
    "vodafone idea": {"ticker": "IDEA", "name": "Vodafone Idea", "mkt": "IN", "sector": "telecom"},
    "paytm": {"ticker": "PAYTM", "name": "Paytm", "mkt": "IN", "sector": "fintech"},
    "zomato": {"ticker": "ETERNAL", "name": "Eternal (Zomato)", "mkt": "IN", "sector": "consumer-internet"},
    "eternal": {"ticker": "ETERNAL", "name": "Eternal (Zomato)", "mkt": "IN", "sector": "consumer-internet"},
    "policybazaar": {"ticker": "POLICYBZR", "name": "PB Fintech", "mkt": "IN", "sector": "fintech"},
    "pb fintech": {"ticker": "POLICYBZR", "name": "PB Fintech", "mkt": "IN", "sector": "fintech"},
    "nse": {"ticker": "NSEIPO", "name": "National Stock Exchange", "mkt": "IN", "sector": "exchange"},
    "nvidia": {"ticker": "NVDA", "name": "NVIDIA", "mkt": "US", "sector": "semiconductor"},
    "nvda": {"ticker": "NVDA", "name": "NVIDIA", "mkt": "US", "sector": "semiconductor"},
    "micron": {"ticker": "MU", "name": "Micron", "mkt": "US", "sector": "semiconductor"},
    "amd": {"ticker": "AMD", "name": "AMD", "mkt": "US", "sector": "semiconductor"},
    "broadcom": {"ticker": "AVGO", "name": "Broadcom", "mkt": "US", "sector": "semiconductor"},
    "tsmc": {"ticker": "TSM", "name": "TSMC", "mkt": "US", "sector": "foundry"},
    "taiwan semi": {"ticker": "TSM", "name": "TSMC", "mkt": "US", "sector": "foundry"},
    "intel": {"ticker": "INTC", "name": "Intel", "mkt": "US", "sector": "semiconductor"},
    "apple": {"ticker": "AAPL", "name": "Apple", "mkt": "US", "sector": "tech"},
    "iphone": {"ticker": "AAPL", "name": "Apple", "mkt": "US", "sector": "tech"},
    "microsoft": {"ticker": "MSFT", "name": "Microsoft", "mkt": "US", "sector": "tech"},
    "amazon": {"ticker": "AMZN", "name": "Amazon", "mkt": "US", "sector": "tech"},
    "alphabet": {"ticker": "GOOGL", "name": "Alphabet", "mkt": "US", "sector": "tech"},
    "google": {"ticker": "GOOGL", "name": "Alphabet", "mkt": "US", "sector": "tech"},
    "meta": {"ticker": "META", "name": "Meta", "mkt": "US", "sector": "tech"},
    "tesla": {"ticker": "TSLA", "name": "Tesla", "mkt": "US", "sector": "ev"},
    "cybercab": {"ticker": "TSLA", "name": "Tesla", "mkt": "US", "sector": "ev"},
    "nike": {"ticker": "NKE", "name": "Nike", "mkt": "US", "sector": "consumer"},
    "exxon": {"ticker": "XOM", "name": "Exxon Mobil", "mkt": "US", "sector": "energy"},
    "chevron": {"ticker": "CVX", "name": "Chevron", "mkt": "US", "sector": "energy"},
    "boeing": {"ticker": "BA", "name": "Boeing", "mkt": "US", "sector": "aerospace"},
    "lockheed": {"ticker": "LMT", "name": "Lockheed Martin", "mkt": "US", "sector": "defense"},
    "raytheon": {"ticker": "RTX", "name": "RTX", "mkt": "US", "sector": "defense"},
    "jpmorgan": {"ticker": "JPM", "name": "JPMorgan", "mkt": "US", "sector": "bank"},
    "goldman": {"ticker": "GS", "name": "Goldman Sachs", "mkt": "US", "sector": "bank"},
    "berkshire": {"ticker": "BRK.B", "name": "Berkshire Hathaway", "mkt": "US", "sector": "conglomerate"},
    "lennar": {"ticker": "LEN", "name": "Lennar", "mkt": "US", "sector": "homebuilder"},
    "quanta": {"ticker": "PWR", "name": "Quanta Services", "mkt": "US", "sector": "grid"},
    "linde": {"ticker": "LIN", "name": "Linde", "mkt": "US", "sector": "industrials"},
    "openai": {"ticker": "MSFT", "name": "OpenAI (Microsoft proxy)", "mkt": "US", "sector": "ai"},
    "anthropic": {"ticker": "AMZN", "name": "Anthropic (Amazon proxy)", "mkt": "US", "sector": "ai"},
    "dlf": {"ticker": "DLF", "name": "DLF", "mkt": "IN", "sector": "realty"},
    "irfc": {"ticker": "IRFC", "name": "IRFC", "mkt": "IN", "sector": "railways"},
    "indian railway finance": {"ticker": "IRFC", "name": "IRFC", "mkt": "IN", "sector": "railways"},
    "bse": {"ticker": "BSE", "name": "BSE", "mkt": "IN", "sector": "exchange"},
    "bombay stock exchange": {"ticker": "BSE", "name": "BSE", "mkt": "IN", "sector": "exchange"},
    "apollo tyres": {"ticker": "APOLLOTYRE", "name": "Apollo Tyres", "mkt": "IN", "sector": "tyres"},
    "phillips 66": {"ticker": "PSX", "name": "Phillips 66", "mkt": "US", "sector": "refining"},
    "delta air": {"ticker": "DAL", "name": "Delta Air Lines", "mkt": "US", "sector": "aviation"},
    "delta airlines": {"ticker": "DAL", "name": "Delta Air Lines", "mkt": "US", "sector": "aviation"},
    "nasdaq": {"ticker": "QQQ", "name": "Invesco QQQ", "mkt": "US", "sector": "etf"},
    "qqq": {"ticker": "QQQ", "name": "Invesco QQQ", "mkt": "US", "sector": "etf"},
    "tlt": {"ticker": "TLT", "name": "iShares 20+ Year Treasury", "mkt": "US", "sector": "etf"},
    "long bond": {"ticker": "TLT", "name": "iShares 20+ Year Treasury", "mkt": "US", "sector": "etf"},
    "gold etf": {"ticker": "GOLD", "name": "Gold (ETF proxy)", "mkt": "IN", "sector": "gold"},
    "bullion": {"ticker": "GOLD", "name": "Gold (ETF proxy)", "mkt": "IN", "sector": "gold"},
}

THEMES = {
    "oil_up": {
        "label": "Crude / diesel prices rising",
        "meaning": "Higher energy costs squeeze refiners' marketing margins, airlines, paints and freight until they pass through price. Upstream and some defense/shipping names catch a bid. Sticky oil also lifts India's import bill, INR pressure and RBI hawkish odds.",
        "keywords": [
            "oil prices", "brent", "crude oil", "crude jumps", "oil hits", "oil surge",
            "diesel price", "fuel prices", "atf", "hormuz", "iran war", "oil supply",
            "$100 a barrel", "oil spike", "petroleum",
        ],
        "negations": [
            "oil lower", "oil drop", "oil fall", "oil retreat", "oil slips", "spr",
            "release diesel", "release of oil", "stockpile release", "strategic reserve",
        ],
        "direct_buy": [
            ("ONGC", "Upstream realisation rises with crude."),
            ("OIL", "Upstream crude leverage."),
            ("XOM", "Integrated US oil cash-flow expands on higher crude."),
            ("CVX", "Integrated US oil cash-flow expands on higher crude."),
        ],
        "direct_sell": [
            ("IOC", "OMC under-recovery / inventory hit while retail prices lag."),
            ("BPCL", "Same OMC margin squeeze."),
            ("HPCL", "Same OMC margin squeeze."),
            ("INDIGO", "ATF is the largest variable cost."),
        ],
        "indirect_buy": [
            ("HAL", "Energy-war geopolitics lifts defense-order optionality."),
            ("BEL", "Defense electronics second-order on conflict premium."),
            ("LMT", "US defense budget / conflict duration."),
        ],
        "indirect_sell": [
            ("ASIANPAINT", "Crude-linked solvents and packaging inflate COGS with a lag."),
            ("PIDILITIND", "Input cost inflation."),
            ("ASHOKLEY", "Diesel cost hits CV operators, then OEM demand."),
            ("MARUTI", "Fuel inflation plus rates hit PV demand."),
            ("TATAMOTORS", "CV + PV volume risk from fuel inflation."),
            ("M&M", "Rural diesel / tractor demand sensitivity."),
        ],
    },
    "oil_down": {
        "label": "Oil / diesel easing (SPR, G7 release, demand scare)",
        "meaning": "A coordinated stock release or demand scare caps the near-term diesel spike. OMCs and rate-sensitive consumers get relief; upstream loses scarcity rent. This is usually a 1-4 week painkiller, not a new supply regime, if wars continue.",
        "keywords": [
            "oil lower", "oil drop", "oil fall", "oil retreat", "oil slips", "brent drop",
            "g7", "diesel stocks", "strategic reserve", "spr", "release diesel",
            "100 million barrels", "iea", "export ban", "stockpile",
        ],
        "negations": ["oil hits", "oil surge", "oil jump"],
        "direct_buy": [
            ("IOC", "GRM / under-recovery relief if crude and diesel ease."),
            ("BPCL", "Marketing margin relief."),
            ("HPCL", "Marketing margin relief."),
            ("INDIGO", "ATF cost peak-out supports yields."),
            ("PSX", "US refiners keep export option if ban is off."),
        ],
        "direct_sell": [
            ("ONGC", "Crude price peak-out cuts realisation."),
            ("XOM", "Less scarcity rent if SPR actually hits the tape."),
        ],
        "indirect_buy": [
            ("ASIANPAINT", "Input-cost relief with a lag."),
            ("MARUTI", "Fuel-inflation pressure eases on PV demand."),
            ("ASHOKLEY", "Fleet operating-cost relief."),
            ("RELIANCE", "Complex: export GRM vs crude; net constructive if diesel cracks stay and ban is off."),
        ],
        "indirect_sell": [
            ("HAL", "Geopolitical premium may fade if energy scare recedes."),
        ],
    },
    "rupee_weak": {
        "label": "Rupee weakening / USDINR up",
        "meaning": "INR depreciation is a translation tailwind for IT and US-dollar pharma exporters, and a cost/CAD hit for oil importers, electronics and foreign-debt names. FPI usually sells high-beta India when the dollar is bid.",
        "keywords": [
            "rupee sinks", "rupee falls", "rupee slide", "rupee dived", "usd/inr",
            "dollar index", "inr ", "rupee hits", "96.31", "weak rupee", "rupee dives",
        ],
        "negations": ["rupee rises", "rupee gains", "rupee recovers"],
        "direct_buy": [
            ("TCS", "USD revenue translates into higher INR sales/EBIT."),
            ("INFY", "Same exporter FX operating leverage."),
            ("HCLTECH", "Same exporter FX operating leverage."),
            ("WIPRO", "Same exporter FX operating leverage."),
            ("TECHM", "Same exporter FX operating leverage."),
            ("SUNPHARMA", "USD formulations realisation."),
        ],
        "direct_sell": [
            ("IOC", "Crude is dollar-priced; INR weak worsens under-recoveries."),
            ("BPCL", "Dollar crude bill."),
            ("HPCL", "Dollar crude bill."),
        ],
        "indirect_buy": [
            ("DRREDDY", "Export mix."),
            ("CIPLA", "Export mix."),
        ],
        "indirect_sell": [
            ("ADANIPORTS", "High-beta / foreign-debt / FPI factor."),
            ("ADANIENT", "High-beta conglomerate sold in INR risk-off."),
            ("TATASTEEL", "Import coal in dollars; FPI cyclical."),
            ("IDEA", "Foreign-debt / importer profile."),
        ],
    },
    "yields_up": {
        "label": "Bond yields / cost of capital rising",
        "meaning": "Higher UST and G-Sec yields re-rate long-duration equity (growth, realty, quality bond-proxies) and pressure bank AFS books. This is often a bigger India-multiple shock than oil. Unsecured NBFCs face funding + valuation hit.",
        "keywords": [
            "bond yield", "treasury yield", "10-year", "10 year yield", "g-sec",
            "bond rout", "borrowing costs", "rate hike", "fed rate", "rbi may hike",
            "repo rate", "hawkish", "highest since 2002", "7.20",
        ],
        "negations": ["rate cut", "dovish", "yields fall", "yields drop", "pause"],
        "direct_buy": [
            ("SBIN", "Floating-rate book / PSU banks often lag but NII can expand if deposit beta lags."),
        ],
        "direct_sell": [
            ("BAJFINANCE", "Duration + wholesale funding + valuation multiple."),
            ("HDFCBANK", "Bond-book / multiple compression in a yield spike, even if NII is mixed."),
            ("KOTAKBANK", "Quality-bank multiple is a bond proxy."),
        ],
        "indirect_buy": [
            ("ITC", "Defensive cash-flow, less duration."),
            ("HINDUNILVR", "Staples relative in a de-rate."),
        ],
        "indirect_sell": [
            ("DLF", "Realty is long rates."),
            ("ULTRACEMCO", "Housing/infra demand lag after rates."),
            ("MARUTI", "Auto loans reprice."),
            ("TITAN", "Discretionary duration."),
            ("ETERNAL", "Long-duration consumer internet."),
            ("PAYTM", "High-duration fintech."),
            ("LEN", "US homebuilder rate sensitivity."),
            ("TLT", "Long bonds fall when yields jump."),
        ],
    },
    "fed_dovish": {
        "label": "Soft jobs / hike odds cut / liquidity bid",
        "meaning": "Weaker US labour data cuts near-term hike odds and can re-bid Nasdaq duration (AI, software). It does not automatically save EM if the term premium stays high. Map to IT/semis first, not to India cyclicals.",
        "keywords": [
            "jobs report", "payrolls", "unemployment", "soft jobs", "job market cools",
            "rate hike odds", "fed pause", "weaker jobs", "nonfarm",
        ],
        "negations": ["hot jobs", "strong payrolls", "wage spike"],
        "direct_buy": [
            ("NVDA", "Duration / AI complex catches a bid when hike odds fall."),
            ("MU", "Memory/AI beta."),
            ("QQQ", "Nasdaq duration."),
            ("TCS", "US financials/tech spend + risk-on overlay."),
            ("INFY", "Same India IT transmission."),
        ],
        "direct_sell": [],
        "indirect_buy": [
            ("AVGO", "Networking/AI ASIC."),
            ("TSM", "Foundry bottleneck."),
            ("HCLTECH", "India IT second-order."),
            ("TECHM", "India IT second-order."),
        ],
        "indirect_sell": [
            ("XOM", "If the move is a growth scare, oil demand pricing can slip."),
        ],
    },
    "ai_boom": {
        "label": "AI / semiconductor capex cycle",
        "meaning": "AI headlines re-rate the constraint, not the TAM slide: GPUs, HBM, foundry, networking, then power/grid/copper. India EMS and IT services are second-order, not NVDA clones.",
        "keywords": [
            "nvidia", "ai chip", "artificial intelligence", "data center", "hbm",
            "semiconductor", "micron", "broadcom", "ai stocks", "gpu",
        ],
        "negations": ["ai bubble", "ai fade", "capex cut"],
        "direct_buy": [
            ("NVDA", "GPU constraint and incremental token demand."),
            ("MU", "HBM tightness."),
            ("AVGO", "Custom ASICs / networking."),
            ("TSM", "Foundry / CoWoS."),
        ],
        "direct_sell": [
            ("INTC", "Share loss vs foundry/GPU complex unless a specific Intel win."),
        ],
        "indirect_buy": [
            ("PWR", "US data-center electrical / grid."),
            ("NTPC", "India power demand from AI/GCCs is a slow grind, not a spike."),
            ("POWERGRID", "Transmission bottleneck."),
            ("TATAPOWER", "Generation + renewables overlay."),
            ("HCLTECH", "AI services attach, with cannibalization risk."),
            ("TCS", "AI services / deal TCV."),
        ],
        "indirect_sell": [
            ("NKE", "Consumer discretionary can be crowded out by AI factor."),
        ],
    },
    "fpi_out": {
        "label": "FPI outflow / EM risk-off",
        "meaning": "Foreign selling is a flow event. It hits high-beta midcaps, promoters with pledges, and crowded quality last. PSU banks and IT often relatively better. Do not confuse with an earnings reset.",
        "keywords": [
            "fpi", "foreign investors", "fii", "pull out", "net sellers",
            "emerging market", "outflow",
        ],
        "negations": ["fpi buy", "inflow", "return to dalal"],
        "direct_buy": [
            ("TCS", "Quality exporter, often a relative shelter when FPI dumps cyclicals."),
            ("INFY", "Same."),
            ("ITC", "Domestic cash compounder, lower FPI crowding than midcaps."),
        ],
        "direct_sell": [
            ("ADANIENT", "High-beta FPI factor."),
            ("ADANIPORTS", "High-beta FPI factor."),
            ("SUZLON", "Retail/high-beta unwind."),
            ("RVNL", "Railway-PSU crowding unwind."),
            ("IRFC", "Same crowding."),
        ],
        "indirect_buy": [
            ("HDFCBANK", "Relative quality if the tape is a flow flush, not a credit event."),
        ],
        "indirect_sell": [
            ("PAYTM", "High-beta fintech."),
            ("ETERNAL", "High-beta consumer internet."),
            ("IDEA", "Weak balance-sheet sold first."),
        ],
    },
    "auto_demand": {
        "label": "Auto sales / GST / rural demand",
        "meaning": "Volume prints move OEMs only if they beat a GST/base-effect distorted number and if rates/fuel are not eating EMI. Ancillaries and NBFCs are the 1-hop.",
        "keywords": [
            "auto sales", "vehicle sales", "pv sales", "two-wheeler", "gst",
            "tractor", "cv sales",
        ],
        "negations": ["auto sales fall", "dispatches drop"],
        "direct_buy": [
            ("MARUTI", "PV volume operating leverage if print is real, not GST pull-forward."),
            ("M&M", "UV + tractor mix."),
            ("BAJAJ-AUTO", "2W / 3W export mix."),
            ("HEROMOTOCO", "Rural 2W."),
            ("ASHOKLEY", "CV cycle."),
            ("TATAMOTORS", "PV + CV."),
        ],
        "direct_sell": [],
        "indirect_buy": [
            ("APOLLOTYRE", "Replacement + OEM."),
            ("BAJFINANCE", "Auto-loan origination, unless yields dominate."),
        ],
        "indirect_sell": [
            ("IOC", "If the story is GST-led pull-forward, fuel demand is not a new regime."),
        ],
    },
    "it_preview": {
        "label": "India IT demand / Q2 preview",
        "meaning": "IT moves on US BFSI/retail spend, deal conversion, USDINR and whether AI is attach or deflation. A 'muted growth, steady margin' preview is usually a relative BUY vs India cyclicals, not an absolute re-rate.",
        "keywords": [
            "it q2", "infosys", "tcs q2", "deal conversion", "ai deflation",
            "it services", "muted growth",
        ],
        "negations": [],
        "direct_buy": [
            ("TCS", "Quality compounder into results; FX tailwind."),
            ("INFY", "Highest beta to US commentary."),
            ("HCLTECH", "Deal pipeline / ER&D."),
        ],
        "direct_sell": [
            ("TECHM", "Typically the first cut if demand is muted."),
        ],
        "indirect_buy": [
            ("WIPRO", "Laggard option if commentary is not a collapse."),
        ],
        "indirect_sell": [
            ("NKE", "Soft US discretionary can be the same consumer that funds IT spend."),
        ],
    },
    "defense_geo": {
        "label": "Geopolitics / defense orders / drones",
        "meaning": "Conflict premium is real for order books but crowded. Prefer names with actual contracts over narrative. Second-order: energy, shipping, gold, INR.",
        "keywords": [
            "ukraine", "drone", "defense", "missile", "war machine", "israel",
            "iran", "houthis", "geopolitics",
        ],
        "negations": ["ceasefire", "peace deal"],
        "direct_buy": [
            ("HAL", "Platform OEM."),
            ("BEL", "Electronics / radars."),
            ("LMT", "US prime."),
            ("RTX", "Missiles / sensors."),
        ],
        "direct_sell": [
            ("INDIGO", "Airspace / ATF / traffic risk."),
            ("DAL", "US airline geopolitical / fuel."),
        ],
        "indirect_buy": [
            ("ONGC", "Risk premium in crude."),
            ("GOLD", "INR + war hedge (use gold ETF / Titan mixed)."),
            ("TITAN", "Gold-price pass-through, demand mixed."),
        ],
        "indirect_sell": [
            ("ADANIPORTS", "Shipping / risk-off beta."),
        ],
    },
    "gold_bid": {
        "label": "Gold bid (INR hedge / real rates)",
        "meaning": "Gold up with yields is a currency/geopolitics hedge, not a classic real-rate trade. Jewellers get inventory mark-up but demand destruction. Miners/ETFs are the clean expression.",
        "keywords": ["gold price", "gold hits", "bullion", "gold rally", "mcx gold"],
        "negations": ["gold slips", "gold fall", "gold drop"],
        "direct_buy": [
            ("TITAN", "Inventory gains; watch volumes."),
        ],
        "direct_sell": [],
        "indirect_buy": [
            ("HDFCBANK", "Not a gold proxy — skip unless the story is INR crisis."),
        ],
        "indirect_sell": [
            ("ETERNAL", "Discretionary squeezed if households rotate to gold."),
        ],
    },
    "consumer_us_weak": {
        "label": "US consumer / Nike-type miss",
        "meaning": "A branded-athletic miss is company-specific until it clusters (guidance cuts across retail). For India it is a soft tell on US discretionary, which is also an IT-spend input.",
        "keywords": ["nike", "forecast", "consumer confidence", "retail sales miss", "guidance cut"],
        "negations": ["beats forecasts", "raises guidance"],
        "direct_buy": [],
        "direct_sell": [
            ("NKE", "Brand + inventory + guidance."),
        ],
        "indirect_buy": [
            ("TCS", "Only if the miss is Nike-specific and USDINR still helps."),
        ],
        "indirect_sell": [
            ("DMART", "Weak analog if global consumer risk-off hits India retail multiples."),
            ("ETERNAL", "Discretionary internet beta."),
        ],
    },
    "ipo_supply": {
        "label": "Large IPO supply (Jio / NSE)",
        "meaning": "A $3-4bn IPO is a flow event: it absorbs domestic liquidity, can pressure related listed names into the print, then re-rate the parent if the listing is clean. Not an earnings event until lock-up/use-of-proceeds is clear.",
        "keywords": ["ipo", "jio platforms", "nse ipo", "draft papers", "public offer"],
        "negations": [],
        "direct_buy": [
            ("RELIANCE", "If Jio IPO crystallises a tracking value higher than the stub; else wait for pricing."),
        ],
        "direct_sell": [
            ("BHARTIARTL", "Relative: a funded Jio is a tougher telecom/digital competitor — mixed, often sold into the event."),
            ("IDEA", "Competitive intensity / liquidity rotation."),
        ],
        "indirect_buy": [
            ("BSE", "Exchange volumes around mega listings."),
        ],
        "indirect_sell": [
            ("PAYTM", "Liquidity rotation out of smaller digital names."),
        ],
    },
    "rbi_hawkish": {
        "label": "RBI hike risk / inflation + oil",
        "meaning": "A 25 bps hike would be about oil/INR, not domestic overheating. Banks' NII mixed; credit growth and realty get the hit. Bond-proxy quality de-rates.",
        "keywords": ["rbi may hike", "repo rate", "mpc", "inflation and oil", "rbi hawkish"],
        "negations": ["rate cut", "dovish rbi", "pause"],
        "direct_buy": [
            ("SBIN", "Asset-repricing, PSU banks."),
            ("ICICIBANK", "Better liability franchise through a hike."),
        ],
        "direct_sell": [
            ("BAJFINANCE", "Growth-NBFC multiple + funding."),
            ("HDFCBANK", "Near-term multiple, even if NII ok."),
        ],
        "indirect_buy": [
            ("ITC", "Staples over duration."),
        ],
        "indirect_sell": [
            ("MARUTI", "EMI."),
            ("ULTRACEMCO", "Housing cycle."),
            ("TITAN", "Discretionary."),
        ],
    },
}

BULLISH_WORDS = (
    "surge", "soar", "rally", "beats", "beat estimates", "record high", "upgrade",
    "raises guidance", "win ", "order book", "inflow", "profit jumps", "strong sales",
)
BEARISH_WORDS = (
    "crash", "plunge", "slump", "misses", "cut forecast", "downgrade", "probe",
    "penalty", "outflow", "loss", "weak", "ban", "fraud", "default",
)

SKIP_TITLES = (
    "horoscope", "zodiac", "wishes", "calculator", "subscribe", "newsletter",
    "sign in", "cookie", "privacy", "epaper", "watchlist",
)